services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./monitoring/loki:/loki
    networks:
      - monitoring
  grafana:
    container_name: grafana
    build: 'monitoring/grafana'
    ports:
      - 3000:3000
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - monitoring
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.44.0
    user: root
    command:
      - --config.file=/etc/prometheus/prometheus-config.yaml
      - --log.level=debug
    ports:
      - 9090:9090
    volumes:
      - ./monitoring/prometheus/prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
      - ./monitoring/prometheus:/prometheus
    networks:
      - monitoring
networks:
  monitoring: