{
 "title": "Request Time",
 "description": "Request Time",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Request Time Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", uri=\"/auth\"}[1m])",
     "legendFormat": "{{method}}-{{status}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Mean response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", uri=\"/auth\"}[1m])/rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{method}}-{{status}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Response time of 95%, 99% of requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", uri=\"/auth\"}[1m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", uri=\"/auth\"}[1m])) by (le))",
     "legendFormat": "95%"
    }
   ]
  }
 ]
}