spring:
  application:
    name: @project.artifactId@
  datasource:
    url: jdbc:postgresql://postgres-server:5432/auth
    username: auth
    password: auth

redis:
  host: redis
  port: 6379
  ttl: 15

app-info:
  artifact-id: ${spring.application.name}
  version: @revision@

header:
  environment: dev
  timeout: 120

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info,metric,env"
      path-mapping:
        prometheus: metrics
  server:
    port: 8080
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      probes:
        enabled: true